### ISSUE TITLE
Loading a Save File only shows the Text from the xml File

### ISSUE THREAD

**Issue by OLStefan** [oddmage/andrummer#1]
Used System: Android 5.0.2, Cyanogenmod 12-20151011-NIGHTLY-a5

Uploaded Screenshot to show what happens, if i try to open a save file.

Happens with every Chummer save file i tried, but uploaded only one of them.
[ChummerAndroid.zip](https://github.com/oddmage/andrummer/files/698706/ChummerAndroid.zip)

**Comment by draffapps** [comment]
Thanks for the reply. The problem is that you tried to load the chummer
file itself, since chummer does a bunch of calculations that I didn't want
to duplicate I made it so that it'll read the XML from the print function.
So if you load your characters then hit print, in the top left the a save
as XML. That should load. Let me know if it works that way for you.
